### ISSUE TITLE
 Мій звіт про результати коміта

### ISSUE THREAD

**Issue by Diana0** [Diana0/MTDIP-Mankevych-MainProject#1]
1. Create GitHub account.
2. Create repository.
![createrepository](https://user-images.githubusercontent.com/8223714/48734420-075deb80-ec4e-11e8-8766-c28ca64bfd32.png)
3. Add collaborator.
![addcollaborator](https://user-images.githubusercontent.com/8223714/48734395-fb722980-ec4d-11e8-8b79-b42458abaf5e.png)
4. Create new txt file with FIO.
![createnewfilegit](https://user-images.githubusercontent.com/8223714/48734077-0c6e6b00-ec4d-11e8-834d-d11167d4fecb.png)
5. Checkout repository via PyCharm, create Calculator.py file, implement basic calculator functionality, commit and push changes to master branch.
![commitfiletogit](https://user-images.githubusercontent.com/8223714/48733858-78040880-ec4c-11e8-9c18-923f296ea285.png)

**Comment by smoktii-igov** [comment]
Ок
